### ISSUE TITLE
Error converting shape to a TensorShape: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by AbhisekTiwari** [maxbren/GO-Bot-DRL#3]
Traceback (most recent call last):

  File "<ipython-input-9-d90f931063ef>", line 1, in <module>
    runfile('C:/Users/hp/Desktop/GOCA_DRL/OS/End To End/1.GO-Bot/train.py', wdir='C:/Users/hp/Desktop/GOCA_DRL/OS/End To End/1.GO-Bot')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/hp/Desktop/GOCA_DRL/OS/End To End/1.GO-Bot/train.py", line 70, in <module>
    dqn_agent = DQNAgent(state_tracker.get_state_size(), constants)

  File "C:\Users\hp\Desktop\GOCA_DRL\OS\End To End\1.GO-Bot\dqn_agent.py", line 50, in __init__
    self.beh_model = self._build_model()

  File "C:\Users\hp\Desktop\GOCA_DRL\OS\End To End\1.GO-Bot\dqn_agent.py", line 66, in _build_model
    model.add(Dense(self.hidden_size, input_dim=self.state_size, activation='relu'))

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 162, in add
    name=layer.name + '_input')

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\input_layer.py", line 178, in Input
    input_tensor=tensor)
 File "C:\ProgramData\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\input_layer.py", line 87, in __init__
    name=self.name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 541, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)

  File "C:\Users\hp\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\array_ops.py", line 1777, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)

  File "C:\Users\hp\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5496, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)

  File "C:\Users\hp\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\op_def_library.py", line 725, in _apply_op_helper
    attr_value.shape.CopyFrom(_MakeShape(value, key))

  File "C:\Users\hp\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\op_def_library.py", line 201, in _MakeShape
    raise TypeError("Error converting %s to a TensorShape: %s" % (arg_name, e))

**Comment by AbhisekTiwari** [comment]
@maxbren 
Please see
